### ISSUE TITLE
Maquetación GDD, portada e índice

### ISSUE THREAD

**Issue by igallegocalvo** [CIFP-Jose-luis-Garci/Thawnen#1]
- [x] Selección de tipografías
- [x] Creación de paletas de color para la GDD
- [x] Creación de portada
- [x] Creación de índice
- [x] Maquetación de la GDD
- [x] Presentación

**Comment by igallegocalvo** [comment]
**TIPOGRAFÍAS**

Creo que estas tipografías podrías estar bien, tanto para títulos en la GDD como para elementos del juego como el menú. En teoría su licencia es para uso personal, no se si @alhgo o @vcalzadaga nos pueden orientar respecto a eso, para ver si podemos usarlas o no. Aquí dejo los links de algunas que he visto y podrían pegar con el caracter:
- https://www.dafont.com/es/odinson.font
- https://www.dafont.com/es/esthajnal.font
- https://www.behance.net/gallery/22172647/Nordic-(Free-Font)
- https://elements.envato.com/es/noatun-typeface-HDSGTU?_ga=2.169068322.2089501398.1636289882-900337420.1636289882
- https://elements.envato.com/haext-bold-SUF97G6?_ga=2.151568442.2089501398.1636289882-900337420.1636289882
- https://graphicriver.net/item/anthu-a-mystical-font/23122762?_ga=2.151568442.2089501398.1636289882-900337420.1636289882

Las tres últimas pueden ser de pago.

Respecto al propio contenido de la GDD, creo que esta fuente podría estar bien, se lee bien y la forma redondeada de la l la hace distinguible de la i mayúscula, que creo que alguna habrá a lo largo de la GDD:
- https://fonts.google.com/specimen/Nunito+Sans?category=Sans+Serif

Respecto a los diálogos del juego, no tengo claro qué tipografía podríamos emplear

**Comment by igallegocalvo** [comment]
**PALETA DE COLORES PARA LA GDD**

Os dejo tres imágenes de paletas de colores para la GDD, si os parece bien, pinchad en el icono de los tres puntos y dadle a quote, creo que así puede estar todo ordenado y lo mismo hasta salta notificación... no lo se. Os dejo las imágenes, luego cuando tengamos una decidida pensamos qué color usar en cada elemento (títulos, tintes para imágenes...)
- Paleta 1
![paleta1](https://user-images.githubusercontent.com/77749840/140649105-2876043d-9574-4ded-b10c-14e868240e61.jpg)
- Paleta 2
![paleta2](https://user-images.githubusercontent.com/77749840/140649106-467de34c-608b-4ec5-b827-4f14b6f1c0fc.jpg)
- Paleta 3
![paleta3](https://user-images.githubusercontent.com/77749840/140649108-69218268-f443-4400-87d4-3f8fa4995e37.jpg)

**Comment by silviamarugan** [comment]
La primera paleta me gusta mucho, creo que es la que mas pega. Si no, la segunda tambien esta bonita

**Comment by Alba-Munoz** [comment]
Si, la primera creo que es la que mejor quedaría con nuestro juego.

**Comment by igallegocalvo** [comment]
**PORTADA**
No tengo muy claro como hacerla pero obviamente tendría que aparecer el logo, que ya lo tenemos por aquí. Quizá estaría bien tener un concept para ponerlo.
El logo se mantiene cierto?

**Comment by silviamarugan** [comment]
En cuanto a tipografías, personalmente me gustan la Odinson (https://www.dafont.com/es/odinson.font) y la Nordic (https://www.behance.net/gallery/22172647/Nordic-(Free-Font)) que podría estar bonita para hacer el titulo de nuestro juego en la portada. Como fuente secundaria me gusta la Nunito Sans o igual hasta podría quedar bien una Lato.

**Comment by igallegocalvo** [comment]
**MAQUETACIÓN**

Os dejo un pdf con la hoja de estilos que he pensado para la GDD, si queréis modifico algo.
[Thawnen_estilos_GDD.pdf](https://github.com/CIFP-Jose-luis-Garci/Thawnen/files/7499278/Thawnen_estilos_GDD.pdf)

**Comment by igallegocalvo** [comment]
**PORTADA**

Os dejo un diseño preliminar de la portada, qué opináis, se pone algún concept o se deja como la portada de la GDD de Sion?
[Thawnen_portada_GDD.pdf](https://github.com/CIFP-Jose-luis-Garci/Thawnen/files/7499575/Thawnen_portada_GDD.pdf)

**Comment by igallegocalvo** [comment]
**MAQUETACIÓN GDD**

Buenas, os dejo por aquí lo que llevo de maquetación, por si creéis que habría que cambiar algún estilo.
Los textos estoy copiando y pegando directamente los que se han ido poniendo en los issues dando por sentado que los temas cerrados no requieren ninguna modificación.
[Thawnen_GDD.pdf](https://github.com/CIFP-Jose-luis-Garci/Thawnen/files/7508892/Thawnen_GDD.pdf)

**Comment by igallegocalvo** [comment]
**TIPOGRAFÍAS**

En el juego no podríamos usar la Odinson por ser su licencia gratuita para uso personal.

**Comment by silviamarugan** [comment]
La Nordic es libre? Podria quedar bien para titulos

**Comment by igallegocalvo** [comment]
Nop, uso personal.
Hay que cambiar tanto la Nordic como la Odinson. O comprarlas.
He encontrado estas dos, que no molan tanto, pero cumplen la estética nordica y son legibles:
- Vinland: https://www.dafont.com/vinland.font
- Norse: https://www.dafont.com/norse.font

Para el título buscaré otra o dejamos la Nordic en la GDD y ya se hará un logo para el juego, o tiramos del que había

**Comment by igallegocalvo** [comment]
**MAQUETACIÓN**

Progreso de la maquetación de la GDD
[Thawnen_GDD.pdf](https://github.com/CIFP-Jose-luis-Garci/Thawnen/files/7523545/Thawnen_GDD.pdf)

**Comment by sxrgi0** [comment]
**MAQUETACIÓN**

Maquetación completa de la G

[Thawnen_GDD.pdf](https://github.com/CIFP-Jose-luis-Garci/Thawnen/files/7530210/Thawnen_GDD.pdf)
DD

**Comment by sxrgi0** [comment]
**MAQUETACIÓN**

Maquetación terminada de la GDD

[Thawnen_GDD.pdf](https://github.com/CIFP-Jose-luis-Garci/Thawnen/files/7530213/Thawnen_GDD.pdf)

**Comment by sxrgi0** [comment]
**MAQUETACIÓN**

Documento de la GDD terminada

[Thawnen_GDD.pdf](https://github.com/CIFP-Jose-luis-Garci/Thawnen/files/7530388/Thawnen_GDD.pdf)
