### ISSUE TITLE
Movimientos y físicas

### ISSUE THREAD

**Issue by igallegocalvo** [CIFP-Jose-luis-Garci/Thawnen#10]
- [x] Controles: durante el juego (si el jugador puede utilizar gamepad y teclado, indicar los controles de ambos dispositivos) y en la navegación por lo menús
- [x] Interacción entre elementos (tenéis un ejemplo en la página 10 de la GDD Sion)

**Comment by igallegocalvo** [comment]
**FÍSICAS**

El juego no tendrá demasiadas físicas, tan solo habrá colisiones del personaje principal con los elementos del escenario y los enemigos. Quizá algún enemigo emplee armas de largo alcance. Es decir:
- personaje-escenario
- personaje-enemigo
- arma enemigo-personaje

No está claro si habrá algún sistema de magia en el juego que nos permita ataques a distancia. En ese caso habría también colisiones: 
- proyectil-escenario
- proyectil-enemigo

**Comment by igallegocalvo** [comment]
**MOVIMIENTOS**

En cuanto a movimientos, tanto Neerâh como los animales en los que nos transformemos y con toda seguridad los enemigos, deberían disponer de mínimo:
- dos animaciones Idle, una corta y una larga
- caminar
- trotar
- correr
- saltar
- giros a izquierda y derecha
- salto
- esquivar (opcional)
- ataque débil (depende de si hay combos, necesitaremos más)
- ataque fuerte (depende de si hay combos, necesitaremos más)
- ataque especial (si lo hubiese)
- ataque a distancia (si lo hubiese)
- colisión débil
- colisión fuerte
- caída por golpe

Habría que decidir si cada animal en el que nos transformemos tendrá distintos movimientos o solo alguno especial y sobre todo saber si las animaciones podrían adaptarse a los esqueletos de los distintos animales o habría que hacer animaciones nuevas, lo cual supondría una carga de trabajo muy importante aunque sean para el nivel tres personajes más un par de enemigos.

**Comment by igallegocalvo** [comment]
**MOVIMIENTOS**

Se me acaba de ocurrir que nuestro personaje podría transformarse empleando los botones de la cruceta analógica de los gamepads y que en ese para que no se note un cambio brusco de personaje, le podría rodear una esfera de agua que podría proporcional un instante de invencibilidad, como si fuese un escudo y si se realiza correctamente en el momento adecuado podría permitirnos bloquear un ataque enemigo, dejar al rival en desventaja y permitirnos usar un golpe poderoso, como si fuese un parry o una contra. Ese movimiento especial, si quisiésemos emplearlo en cualquier otro movimiento requeriría un tiempo de carga, pero al ejecutar la maniobra de transformación correctamente, nos permitiría usarlo al instante.

**Comment by igallegocalvo** [comment]
**CONTROLES MANDO**
![controlCombateExploracion](https://user-images.githubusercontent.com/77749840/141178067-fae0e524-31dd-4ed7-8def-8f542e02ff24.jpg)

**Comment by igallegocalvo** [comment]
**CONTROLES MANDO**
![controlMenuDialogo](https://user-images.githubusercontent.com/77749840/141178996-bfc537d8-c614-42f2-ad4d-033574b2f57e.jpg)

**Comment by igallegocalvo** [comment]
**CONTROLES**

Ya que somos un zorro y en teoría carecemos de un inventario, quizá sea buena idea el poder usar las almas para curarnos (almas puras) o subirnos el ataque (almas de sangre) durante las peleas y la aventura en general.
Estas almas se consumirían en "paquetes" de 50 por ejemplo y quizá este consumo podría dictar si nos vamos hacia el lado luminoso o al lado oscuro.
Si esta mecánica se implementa, podría estar bien asignar el consumo de las almas a los gatillas L2 (almas de sangre) y R2 (almas puras). Daríamos más sentido a su recolección, a la exploración y al sistema de balanza bien/mal.
Prescindiríamos así del ataque a distancia tal y como está configurada ahora mismo el mapeo de controles o podríamos hacer ese ataque a distancia con combinación de botones.

**Comment by sxrgi0** [comment]
**CONTROLES TECLADO**

Faltan asignar las teclas para seleccionar la transformación, no sé si tenéis idea de donde ponerlas.

![controles_teclado](https://user-images.githubusercontent.com/77583797/141293062-329bc269-3100-4911-8c85-332c86fe6fa9.jpg)

**Comment by sxrgi0** [comment]
**CONTROLES**

![controles_teclado](https://user-images.githubusercontent.com/77583797/141339054-b6591eb4-48cb-4b93-9dc0-eaf55d933718.png)

**Comment by sxrgi0** [comment]
**CONTROLES**

![controles_teclado_menu_dialogos](https://user-images.githubusercontent.com/77583797/141339141-d22fc699-a108-4b67-92bf-133c023b02ca.png)
