### ISSUE TITLE
Diseño de niveles

### ISSUE THREAD

**Issue by igallegocalvo** [CIFP-Jose-luis-Garci/Thawnen#11]
- [x] Objetivo del jugador
- [x] Flujo de juego: explica el transcurso de una partida, los pasos a seguir desde que el juego arranca hasta completar un nivel completo.
- [ ] Niveles del juego: describir sus características principales, los enemigos u obstáculos que encontrará el jugador, con especial incidencia en el nivel que tenéis pensado desarrollar para la práctica final
- [ ] Dificultad: hablad de la progresión de la dificultad durante el juego. Os aconsejo
elaborar un diagrama similar al de la pag 14, tema 
- [x] Tutorial: cómo lo vais a integrar. Vais a utilizar texto o no. Influencias de otros títulos en los que os habéis inspirado.

**Comment by igallegocalvo** [comment]
**OBJETIVO**

El objetivo del usuario es recorrer los distintos niveles del juego recolectando almas puras y de sangre para ayudar a las almas en pena y devolver a la naturaleza a su estado original. 
En cada nivel, el jugador encontrará un jefe final, un jefe intermedio, varios enemigos menores, un par de almas en pena "de la historia" y alguna más oculta de difícil acceso.

**Comment by igallegocalvo** [comment]
**FLUJO DE JUEGO**

Dejo un diagrama de flujo de juego
![flujoJuego](https://user-images.githubusercontent.com/77749840/141275332-6cc6ef74-d569-41bb-8af4-94a72bee78a1.png)

**Comment by silviamarugan** [comment]
FLUJO DE JUEGO Y TUTORIAL: el primer nivel con el tutorial implementado iría en el siguiente orden:


La primera vez que arranca el juego, sale la pantalla de título de nuestro juego "Thawnen", se ve también que lo hemos creado nosotros ya que pone nuestros nombres o el nombre de grupo, habrá un fundido a negro y saltará la cinemática inicial en la cual vemos que hay unos campistas en un llano entre unos arbustos riendo y comiendo en grupo y que tienen armas, vemos cómo Neerah está entre uno de esos arbustos caminando para ir hacia otro lugar. Uno de los campistas se alerta por el ruido y les dice a los demás que bajen el tono, anda con sigilo hacia donde se escuchan las ramas crujir. Aparta unas hojas del arbusto y ve que Neerah está ahi, paralizada por el miedo. Saca un arma y vemos cómo le apunta a la cabeza, espera tres segundos y se ve otro fundido a negro. En todas las cinemáticas y el juego se escucha música que combine con las escenas, en la principal se escucha música de tensión mientras que a partir de aquí es una música más relajada. Después de esto, entraremos en el menú inicial que cuenta con "Juego nuevo","Continuar" en gris, "Configuración", "Galería" y "Créditos". Le daremos a la X para comenzar una nueva partida. Cuando comencemos una nueva partida, nos saldrá una corta cinemática de situación en la que Neerah está en medio del bosque despertando gracias a una bolita de luz que le dice que se despierte, que ya es su hora. Neerah se sobresalta y se levanta rápido pero le fallan las patas debido al dolor, se queja. La bolita se acerca a su herida y solo con eso la cura, además le cuenta lo que ha pasado y le dice que es la única salvación del bosque, por lo que Neerah decide salvar al bosque. Empieza la jugabilidad, cuando das el primer paso, la bolita te cuenta que hay un "punto central" al que debéis ir, por lo que andáis durante un minuto por las profundidades del bosque mientras te cuenta más cosas sobre lo que pasó y sobre cómo se apena por ti. Al llegar al bosque te dice "Se que estás muy débil, pero déjame enseñarte un par de cosas. Quizas te vengan bien para salvarnos, Neerah. Yo ya estoy muy vieja para ayudar en estas cosas, pero puedo usar parte de mi poca energía para enseñarte esto" y hace spawn de un pequeño bichito y empieza a decirte lo que tienes que hacer mientras el bicho se acerca a ti lentamente "con la x puedes rodar por el suelo para esquivar ataques". Salta un texto abajo centrado que pone "X: rodar" Ruedas. "Muy bien, así, te permite hacerlo hacia cualquier dirección". "Con el cuadrado puedes saltar muy alto". Salta un texto abajo centrado que pone "[]: Saltar"  Saltas. "Lo vas pillando". "Prueba a atacarle con O o ∆, O es tu ataque con más poder, mientras que la ∆ te servirá para cuando necesites más rapidez de ataque". Salta un texto abajo centrado que pone "∆: ataque rápido. O: ataque fuerte" Atacas. El bicho se muere. La bolita vuelve a hablar: "Has conseguido un alma. Este alma es de un recuerdo mío, así que es incolora, pero te encontrarás almas de varios tipos según avances, se que es algo confuso pero pronto lo entenderás. Puedes hacer que estás almas velen en paz acercandolas al agua y dejando que fluyan acercándote a aquel monolito y pulsando X" Te acercas al lago, salta un texto abajo centrado que pone "x: purificar". Purificas. "Muy bien, te acompañaré un rato, creo que estás preparada pero tengo que asegurarme de que no te pase nada". La bolita se mueve Salta un texto abajo centrado que pone "Joystick: moverte", la sigues. Pasan unos segundos "Por cierto, no te preocupes por morir, se que nunca es agradable pero eres un alma. No podré acompañarte en tu aventura, pequeña, pero siempre estaré ahí para asegurarme de que tu alma vuelva a tu cuerpo intacta. Aunque ten cuidado porque lo que recolectes volverá al lugar de donde salió, a no ser que lo purifiques o lo intercambies en algún sitio antes". Andamos, se generan enemigos pequeños, los vas matando. La bolita va hablando "muy bien", "sigue así". Se cruza una ardilla con la espalda rota, os parais a hablarla. Os dice "¿Podéis ayudarme? Ayer iba caminando tranquila por el bosque cuando me crucé con una trampa para osos, juro que no la vi. Lo siguiente que recuerdo es sangrar, mucho dolor y tener la columna vertebral rota. No quiero seguir viviendo por favor, liberame del dolor". La bolita dice "Mira Neerah, tienes que ayudar a los animales del bosque, a veces será duro porque no te pedirán cosas fáciles de hacer, pero los animales siempre han sido muy agradecidos. Cuando llegues a la cima del monte, todos los sacrificios que tengas que hacer tendrán sentido"  Salta un texto de "X: absorber alma". La bolita te dice "Ahora, deberías llevarla a un lago a que descanse en paz" Andáis, llegáis al lago, purificas. La bolita habla "Esta vez lo has hecho bien, fíjate que en tu inventario tienes ahora el alma purificada de la ardilla, cuando la actives con su botón correspondiente, tendrás un tiempo limitado para usar su habilidad. Activala ahora." Salta un texto abajo centrado que pone "1: habilidad". Pulsas. La bolita te dice "Prueba a moverte, ahora eres mucho más ágil. Por cierto, te queda bien ser una ardilla". Salta el mensaje de movimiento. "Puedes desactivarla para no consumirla entera con la tecla F, está divertido verte así pero te será útil guardarla para más adelante" La desactivas. Andáis, llegáis a un llano, la bolita dice "Bueno, no me queda mucha energía, pero esta es la prueba definitiva para dejarte ir, cariño". La bolita avanza un poco más "Tengo el recuerdo marcado de la chica que acabo con mi vida, quizás pueda materializarlo y, si te enfrentas a ella, te recompensare con algo que te ayudará a abrir aquella puerta de enfrente y podrás seguir con tu destino". Materializa a la Cazadora de Lobos. Sale su nombre con una barra de vida en la parte central superior. Usas lo aprendido. La bolita va dando indicaciones si te cuesta vencerla; "¡Esquiva!", "Neerah cuidado", "Ahora está indefensa",... Si la vences, te quedas con su alma y la bolita dice "Eso es un alma de sangre, normalmente se usan para desbloquear caminos, aunque hay algunos los cuales puedes desbloquear con las almas que purifiques. Cada puerta es distinta y te pide otra cosa, según necesite para abrirse. Ve a la puerta y sigue tu camino, yo iré a casa a descansar, necesito estar fresca por si te pasa algo". Vas a la puerta, sale un texto abajo centrado que pone "x: requisitos". Sale un pop up que pone que necesitas solo el alma que tienes. Debajo del pop up sale el texto "pulsa x de nuevo para confirmar". Confirmas. La puerta se abre. Luchas con varios enemigos pequeños. Pasas cerca de un lago y espantas a unos peces que había por ahí. llegas al primer boss, El Pescador, el cual se enfada por haberle espantado los peces. Antes de combate te dice "Prepárate para ser pescado". Tira su caña, se engancha con el anzuelo cerca de ti, hace un DASH. Después de este movimiento hay unos segundos entre el siguiente movimiento. Gira su caña en el aire, vuelve a hacer dash a donde te hayas movido esquivando. Segundos de espera. Usa su caña de látigo. Espera. Invoca un pez gigante fantasmal que hace tres ataques con la cola tumbado en el suelo. El pez desaparece. Dash. Segundos de espera. Usa la caña como lazo, falla. Repite el patron de ataque con pequeños cambios hasta que le quitas media vida. Cuando está a media vida, sale una cinemática en la que se le ve andando hacia la barca y te dice "Volveremos a vernos si me vuelves a molestar". Recoge la caña, saca la pala y se va por el lago. Vuelves a controlar al personaje principal. Te encuentras con un gato, el cual te pide que le busques algo de comer. Cuando le traes comida te dice "bueno, realmente creo que ya he vivido suficiente. Quiero decir, me he gastado mis primeras 6 vidas y ahora solo me queda una. Soy un poco cobarde porque nunca le tienes miedo a la muerte hasta que ves que se acerca a ti de manera peligrosa. ¿Como lo harán los humanos, que solo tienen una? ¿Vivirán atemorizados todo el rato? Ah en fin, creo que será mejor asegurarme de descansar en paz, podrías llevarte mi alma a un lugar seguro y libre de muerte?" Salta el botón de pulsar x para absorber alma. Absorbes su alma. Te da las gracias con voz moribunda pero suave y su cuerpo se esfuma. Quedas libre por el mundo para ir descubriendo nuevos caminos, abriendo más puertas, derrotando a más enemigos y descubriendo más partes de la historia.

**Comment by InGar-Akuma** [comment]
Este podría ser el mapa con las localizaciones de los bosses, animales, monolitos y la tienda
Neerah apparecería donde pone inicio y Naneth nos llevará hasta Hëra. De ahí avanzamos en el nivel 1 (tutorial) hasta el pescador en el puente. Entonces, al quedar libres para explorar el mapa, nos encontramos al salmón para poder nadar por el agua y, arriba del todo, el gato.
Al llegar al búho, podría decirnos que en las montañas cerca del mar cuenta una leyenda de que todavía queda un vikingo, pero que necesitamos poder volar para ir por esa zona. Así volvemos atrás en el mapa para darle más uso. Después de vencer al campista, desbloqueamos el cuervo y vamos a las montañas. Conseguimos derrotar al vikingo y la habilidad del reno. Al bajar, nos encontramos otra vez al pescador. Ahora podemos ir a por el cazador.

![Thawnen (2)](https://user-images.githubusercontent.com/77485516/141507147-6504b833-8fc4-4a8f-8a55-38738e09d852.jpg)

**Comment by InGar-Akuma** [comment]
Los niveles van marcados por los bosses, de forma que el nivel 1 termina con el pescador, el nivel 2 con el campista, el nivel 3 con la segunda pelea contra el pescador, y el nivel 4 y último con el cazador. Además, las zonas del mapa respectivas a cada nivel estarán bloqueadas por Corrupción. Para eliminar la Corrupción habrá que entregarle almas a los brotes de las últimas semillas de Hëra.

**Comment by InGar-Akuma** [comment]
En cuanto a la dificultad, la complejidad de las peleas aumentará significativamente según se avanza en el juego (daño de los ataques, los ataques en sí, la vida de los enemigos, el sistema de pelea), por lo que habrá que conseguir las habilidades de los animales para que nos ayuden. Por ejemplo, para derrotar al campista, es recomendable tener al búho equipado para ver en la oscuridad, y para el cazador, habrá que acercarse en sigilo, por lo que se necesitará al gato.
Además se pueden subir el ataque, defensa y vida de Neerâh temporalmente comprando en la tienda.

**Comment by silviamarugan** [comment]
La dificultad irá creciendo a medida que avancemos, tal y como dice Inés. Para ilustrar como irá creciendo a medida que avancemos, nos hemos basado en la siguiente gráfica:
![curva-dificultad-videojuegos.jpg](https://user-images.githubusercontent.com/77985556/141505890-29047613-adc5-485a-a574-5dfa78699cee.jpg)
