### ISSUE TITLE
Referentes

### ISSUE THREAD

**Issue by igallegocalvo** [CIFP-Jose-luis-Garci/Thawnen#13]
Otras obras (videojuegos, libros, películas… ) que os han influido para diseñar el juego. Por cada título que mencionéis, tenéis que indicar en qué aspectos concretos os habéis inspirado

**Comment by sxrgi0** [comment]
**Referentes:**

Spirit of the North: Hemos decidido usar la mecánica de poder dejar atrás el cuerpo físico del personaje principal para poder transformarse en distintos animales para la resolución de puzzles.

Lost Ember: En este juego también podemos transformarnos en distintos animales, pero estos animales deben encontrarse dentro de nuestro campo de acción. Además, también nos hemos inspirado en su aspecto Low Poly.

Saga Ori: Nos hemos inspirado en la utilización de pozos de espíritus, donde el jugador puede descansar y crear un vínculo que usará para transportarse a otro pozo de espíritus. Además, en el juego tienes que restaurar distintas zonas del bosque que han sido sucumbidas por un cataclismo. 

Fe: En este juego debes ayudar a todas las especies del bosque y purificar el bosque. También, nos hemos inspirado en su aspecto visual.

**Comment by sxrgi0** [comment]
No sé si conocéis de algún otro juego, libro o película que nos pueda servir como referente.

**Comment by igallegocalvo** [comment]
Otro referente podría ser Okami, un juego en el que la naturaleza también estaba en decadencia y tenías que hacer florecerla de nuevo. Además eres un lobo.

También tendríamos juegos como Zelda en cuanto a exploración y aventuras.

La serie Happy Three Friends por la mezcla de dibujo cartoon con violencia.

Pokémon por la selección de acompañantes.
