### ISSUE TITLE
Alcance

### ISSUE THREAD

**Issue by igallegocalvo** [CIFP-Jose-luis-Garci/Thawnen#14]
Según vuestra previsión inicial, indicando hasta dónde tenéis pensado desarrollar de aquí al mes de marzo, si vais a modelar los personajes desde cero, en qué aspectos vais a utilizar material de librerías…

**Comment by Alba-Munoz** [comment]
Creemos que como mucho y con el tiempo que tenemos se harán uno o dos niveles y la animática inicial.

**Comment by silviamarugan** [comment]
Tenemos pensado coger assets de librerías gratuitas para los entornos y escenarios, como bosques, ríos. terrenos, pero además modelar personajes y objetos específicos como los bosses, nuestro protagonista, la forma del mapa, y algunas otras cosas más. Como es un juego complejo, haremos que quede bonito pero sin perder mucho tiempo en modelados y nos centraremos más en el apartado de programación, animaciones y coherencia de la historia.
