### ISSUE TITLE
Público objetivo (target)

### ISSUE THREAD

**Issue by igallegocalvo** [CIFP-Jose-luis-Garci/Thawnen#15]
Cuanto más específico mejor, relacionando los datos con el anuario de AEVI

**Comment by InGar-Akuma** [comment]
Nuestro juego tendría un PEGI 16 dada la violencia y sangre que vamos a meter. Por tanto, el público objetivo estaría situado entre los 16 y 30 años mas o menos. Además, los géneros más jugados durante el 2020 son acción y aventura, y los rangos de edad con más jugadores respecto a la población de España están entre los 15-24 y 25-34 años, lo que se ajusta a las especificaciones de Thawnen para alcanzar un mayor número de ventas.
