### ISSUE TITLE
Equipo humano

### ISSUE THREAD

**Issue by igallegocalvo** [CIFP-Jose-luis-Garci/Thawnen#16]
- Relación de los miembros del equipo con los perfiles profesionales vistos en el tema 3. ¿De qué os vais a encargar cada uno?
- Background del equipo. Un breve recorrido por la historia del equipo y sus componentes. Se recomienda incluir alguna fotografía dentro del entorno de trabajo. Por ejemplo: una reunión del equipo de trabajo, programando, diseñando bocetos para el juego…
- [x] Sergio
- [x] Iván
- [x] Inés
- [x] Silvia
- [x] Alba

**Comment by silviamarugan** [comment]
Nuestro equipo se compone de:

- Sergio Fernández: Programación y modelado
- Iván Gallego: Modelado, texturas, arte, programación
- Inés García: Animación, modelado, texturas
- Silvia Marugan: Diseño del videojuego, diseño de arte, modelado
- Alba Muñoz: diseño de arte, modelado

**Comment by silviamarugan** [comment]
Yo soy Silvia, me dedico al diseño del videojuego, el diseño del arte y algo del modelado del videojuego "Thawnen". Además puedo ayudar con los demás puntos del videojuego como la animación, programación... Y podría encargarme de conseguir gente que nos ayude con apartados como la música, el desarrollo, marketing, etc.

Decidí encargarme de estos puntos ya que soy muy fan del arte, me encanta el dibujo y la ilustración. Además, la idea principal de la historia fue mía, por lo que soy quien, en la mayor parte, se encarga de desarrollar los personajes y la historia, además de como se ira construyendo.

Mi recorrido por el mundo audiovisual empezó con un grado medio de Video Disk-Jockey, aunque desde hace unos años ya toqueteaba Blender y otros programas de edición y dibujo, así que estos puntos se me dan bien.

**Comment by Alba-Munoz** [comment]
Yo soy Alba Muñoz, estoy encargada del diseño de arte y modelado en nuestro videojuego, Thawnen,.

Desde siempre me ha gustado dibujar, de hecho estuve yendo a una academia de dibujo durante varios años y  casi todas las optativas que tuve en bachillerato eran de artes(Imagen y sonido y dibujo artístico).

Creo que al tener varios conocimientos sobre este tema voy a resultar más útil que en cualquier otro apartado.

En cuanto al modelado, tampoco se me da mal y también me gusta.

**Comment by igallegocalvo** [comment]
Soy Iván Gallego y me ofrecí prácticamente como comodín, ya que me resultan interesantes todas las opciones que nos dio a elegir Álvaro a la hora de conformar los equipos. No tenía preferencias y puedo echar una mano con lo que sea.

Después de 12 años trabajando como técnico de sonido tanto en directo como en estudio, debido al parón en el sector ocasionado por la pandemia de Covid-19 decidí no quedarme de brazos cruzados y estudiar el ciclo formativo de Animación 2d y 3d, juegos y entornos interactivos también por curiosidad. Siempre he dibujado como hobby (muy influenciado por la estética manga) y tenía ganas de saber cómo se hacían las series y películas de animación y videojuegos (aun sin jugar demasiado).

Esa curiosidad me llevó a estudiar un certificado de Creación de páginas web.

Actualmente lo que más me interesa es la programación y aprender todo lo posible acerca de modelado y texturizado, sobre todo de seres vivos.

**Comment by InGar-Akuma** [comment]
Yo soy Inés, me encargo del modelado, texturizado y animación de los personajes, escenarios y props, por lo que soy artista 3D en este proyecto.

Siempre me ha fascinado el mundo de la animación 2D y 3D, y cómo con estas técnicas hay una mayor libertad a la hora de crear historias que en el cine tradicional. Además, permiten tanto reflejar fielmente la realidad como abstraerse completamente de esta.

Por eso decidí estudiar animación 3D. En concreto, me interesa el modelado, texturizado y animación de seres vivos. Mi meta es crear mundos de fantasía y poder contar historias a través de la animación 3D o de videojuegos.

**Comment by sxrgi0** [comment]
Soy Sergio, me encargo de la programación y modelado del juego.

Siempre he querido estudiar programación y desde hace unos años empecé a interesarme más por la programación orientada a videojuegos así que por ello decidí encargarme de la programación. Además, he descubierto que también me atrae mucho el modelado 3D, así que puedo echar una mano.

En cuanto al resto de tareas, puedo ayudar un poco a mis compañeros si encuentran algún problema.
