### ISSUE TITLE
Actividad diagrama de Gantt

### ISSUE THREAD

**Issue by InGar-Akuma** [CIFP-Jose-luis-Garci/Thawnen#24]
- [x] PDF
- [x] JPG
- [x] Gantt

**Comment by InGar-Akuma** [comment]
Cuadro resumen con las tareas
[Produccion_Thawnen.pdf](https://github.com/CIFP-Jose-luis-Garci/Thawnen/files/7706687/Produccion_Thawnen.pdf)

**Comment by igallegocalvo** [comment]
![GanttThawnen](https://user-images.githubusercontent.com/77749840/145881579-ed448b74-fee6-4ad0-88ab-0398cfe58aff.jpg)
Diagrama de Gantt del proyecto.
