### ISSUE TITLE
Cambio del proyecto a URP

### ISSUE THREAD

**Issue by igallegocalvo** [CIFP-Jose-luis-Garci/Thawnen#25]
Es complicado pasar al URP? Hay que hacer algo muy específico?
Ya que hemos encontrado los tutoriales de texturas, o al menos algunos, no se qué nos compensa más, si trabajar en substance o utilizar los shaders de Unity directamente.
Aun nos queda para texturizar, pero por ir concretando o sabiendo qué es más asequible a la hora de hacer y renderizar el juego.
También es por hacer el cambio antes de empezar a crear las escenas de menús, que es algo que podemos ir haciendo ya.
@alhgo qué nos recomiendas?

**Comment by alhgo** [comment]
Ya lo hemos actualizado a URP, así que todos los repositorios deben sincronizarse. Es algo de lo que os iba a hablar en clase precisamente. Doy por cerrado este issue
