### ISSUE TITLE
Género

### ISSUE THREAD

**Issue by igallegocalvo** [CIFP-Jose-luis-Garci/Thawnen#3]
- [x] Género principal o combinación de géneros que tendrá el videojuego

**Comment by InGar-Akuma** [comment]
Los géneros principales del juego son una mezcla de tres. Por un lado, es de aventura, ya que hay que explorar el mapa, hablar con otros espíritus y seres, e investigar cómo acceder a otras partes del mapa mediante rompecabezas sencillos. También es un juego de acción, ya que hay combates con otros personajes. Por último, tiene rasgos RPG. Neerah puede adquirir y subir de nivel sus habilidades mediante almas y power ups.
