### ISSUE TITLE
Plataforma

### ISSUE THREAD

**Issue by igallegocalvo** [CIFP-Jose-luis-Garci/Thawnen#4]
- [x] Consola, pc, aplicaciones móviles… Justificar por qué habéis elegido esa
plataforma

**Comment by InGar-Akuma** [comment]
Dados los requisitos de hardware que exigirá nuestro juego al ser 3D, se desarrollará para plataformas más potentes como PC y consola. Aunque es un juego narrativo, más común en juegos de PC, hay un mayor uso de consolas (32% de los dispositivos utilizados en 2020), por lo que hemos decidido que sea tanto para consolas como para PC. De este modo, será accesible a un mayor número de posibles compradores.
