### ISSUE TITLE
Historia y narrativa

### ISSUE THREAD

**Issue by igallegocalvo** [CIFP-Jose-luis-Garci/Thawnen#5]
- [x] Lema
- [x] Historia
- [x] Plot points
- [x] Narrativa: indicar qué tipo de narrativa o narrativas se adaptan más a la historia de
vuestro juego y por qué, qué aporta al jugador, qué ventajas e inconvenientes tiene…

**Comment by silviamarugan** [comment]
Hola chicos, ¿como vais? Esto es lo que llevamos de historia, por si os apetece aportar o cambiar algo: 

"Nos encontramos en el año 2054, dentro del bosque Iaur, ubicado en un país nordico muy lejano. En este bosque viven animales muy diversos, en armonía y en paz. Las almas de aquellos que mueren llegan al más allá a través del Árbol Hëra (Juira), suben hasta la copa y se acaban canalizando en frutas de la vida y se encargan de mantener la armonía en el bosque desde el más allá. La humanidad encontró este árbol y acabo comercializando esta fruta cada vez más cuando caía al suelo, pero llegó un punto en el que querían más y más y llegaron a talar el árbol para conseguir las frutas más altas. A partir de aquello, nadie se encargaba de mantener el bosque excepto los animales, ya que las almas no podían descansar en paz y se quedaban en un limbo eterno. Los animales terrenales no podían con todo lo que los humanos hacían a ese bosque, así que todo acabó deteriorándose más y más. 
Los humanos visitaban el bosque constantemente, de vez en cuando por ocio, de vez en cuando por caza, pero de alguna manera siempre acababan perjudicandolo. Dejaban basura, quemaban árboles y plantas, mataban animales a sangre fría y por diversión, destruían lugares para convertirlos en edificios gigantes y otras muchas cosas más. El bosque acabó siendo más pequeño, pero además, más oscuro, vacío, triste. Sólo había unas pocas zonas que no habían sido descubiertas por los humanos que seguían alegres y llenas de naturaleza. 
En un momento, unos humanos decidieron acampar en un lugar del bosque. Llevaban armas y disfrutaban de matar animales, pero no eran cazadores. Un zorro llamado Neerah se escabulló en unos arbustos cercanos para observar su comportamiento por si eran peligrosos, pero uno de ellos se dio cuenta, sacó un arma y le mató. Poco a poco, fue matando a los otros zorros que esperaban una alerta o una buena noticia. 
Neerah no se convirtió en un alma normal, le reconocomia el no haber dado el aviso de aquello que pasó. Quizas por ello despertaba cada 100 años en el mismo lugar en el cual pasó y vagaba por las zonas en las que pasaba en vida. De vez en cuando se encontraba más almas en pena, pero al cabo de un rato se esfumaban; eran más débiles que ella.
Una de estas veces, por pura casualidad, se despertó y se dio cuenta de lo mal que estaba todo el bosque; vio a animales sufriendo, la forestación sucia, quemada y llena de basura, y pensó que quizas si hacía algo al respecto su alma descansaría en paz por fin. Aunque, ¿como lo haría ella sola si es un alma solitaria vagando por ahí y ni siquiera sabe por dónde empezar? Por otra casualidad de la vida, fue andando hacia una pequeña aldea abandonada que se formó con el paso de los años alrededor del tocón gigante del antiguo árbol. En una de las casas se escuchaba un pequeño retintineo, aunque cuando entró no vio nada. Abrió un baúl y de allí salió una bola de luz blanca. Era otra alma en pena, la cual tenía las mismas intenciones que ella pero no podía salir de la aldea ya que se encargaba de que no se viniera abajo. Las dos hablaron y la extraña bola de luz le enseñó lo que podía hacer, como transformarse en otros animales. Después de un rato Neerah partió hacia la montaña más alta, en la cual aquella bola le dijo que encontraría la paz. En el camino, se encuentra a un cuervo moribundo, que le pide que se lleve su alma con ella y la use bien. Neerah la usa y se da cuenta de que ahora puede volar, aunque por tiempo limitado porque es un alma muy vieja.
Así, nuestra protagonista va avanzando por la historia, ayudando a animales a encontrar la paz y además, combatiendo a humanos para saciar su sed de venganza. 
Después de todos los combates y los problemas que ha tenido, llega a la montaña, purifica todas las almas que ha reunido y empieza a nevar mientras se la ve en la escena final, se acaba viendo todo el mapa por el cual hemos pasado. El alma de Neerah se esfuma y se convierte en una bola de luz, junto a las almas que has purificado, se reúnen todas en forma de árbol y avivan el bosque."

**Comment by igallegocalvo** [comment]
**HISTORIA**

Hola Silvia, la historia me gusta, pero yo quizá pensaría otro power up como inicial, volar ya mola mucho y por ejemplo, en Pokémon creo que era de los últimos que te daban. Los primeros creo que eran fuerza y corte.
Quizá, si Neerâh se encuentra con un obstáculo que haya que romper o mover, podríamos cambiar el cuervo por un animal terrestre (tipo oso o jabalí) que nos permita usar "fuerza" y así no tenemos que implementar de cara a programación una mecánica extra como es el vuelo. 
A nivel tutorial creo que es más sencillo una habilidad más simple como empujar o romper que volar, ya que meter el vuelo en los primeros compases del juego sin tener dominados los controles básicos, podría ser demasiado complicado para el usuario.

**Comment by igallegocalvo** [comment]
**HISTORIA**

Y en la parte en la que Neerâh va a una aldea... ojo, tenemos que ser conscientes de los plazos que tenemos y lo mismo, si modelamos una aldea la liamos un poco y no llegamos. Podemos buscar assets si, pero tenemos que ir también con ojo con el tema tiempos, tenemos varios proyectos y tenemos que llegar a todos.
Quizá esa parte se puede simplificar haciendo que la bolita despierte a Neerâh antes de tiempo simplemente y a partir de ese punto iniciar un tutorial en el bosque con los movimientos básicos, el primer NPC al que ayudar con su primer power up, la primera pelea...
Todo el tema previo al despertar se puede hacer como si fuese una animática, con dibujos interesantes y textos, la intro del juego.
Si nos vemos capacitados para modelar la aldea o encontramos una en la asset store bien, pero si no, creo que debemos simplificar todo lo que podamos manteniendo un producto lo más atractivo posible. 
Que ojo, lo mismo estoy pecando de conservador o aguafiestas...

**Comment by silviamarugan** [comment]
Claro! El principio se hará con una cinemática hasta despertar, eso explicará el por qué nos encontramos en la situación en la que estamos. En cuanto a la habilidad, era un ejemplo de lo que pasará en la historia, pero claro que se puede cambiar! Quizás pegue una ardilla o algún tipo de roedor? O algún animal más simple, si. En cuanto a lo de la aldea, lo veía bien por el hecho de tener un punto central en el mapa que de alguna manera te obligue a usar el viaje rápido (ya sea porque en ella puedes encontrar partes de la historia, haya una especie de tienda o quizás vayan animales de vez en cuando a pedir ayuda) pero todo es mirarlo, obviamente todo depende del tiempo y de como de pillados vayamos. Como alternativa me gusta la idea que has aportado.

**Comment by Alba-Munoz** [comment]
Iván, en cuanto a los plazos, si al final se van a hacer como mucho dos niveles, esto al ser el apartado de la historia se tiene que poner completa aunque no se vaya a hacer

**Comment by Alba-Munoz** [comment]
Como lema, esto es lo que habíamos pensado: _Una aventura con toques de acción y RPG en la que el agua y la naturaleza tienen un papel clave._

**Comment by igallegocalvo** [comment]
**LEMA**
Ok, apuntado

**Comment by silviamarugan** [comment]
Como Plot Points hemos pensado estos: 
La destrucción del arbol Hëra. La muerte de Neerâh. Su resurrección. El momento en el que descubre que la bolita es el espíritu de su madre. 

Creeis que falta alguno más? Casi todos los que he mencionado están al principio

**Comment by silviamarugan** [comment]
Como narrativa, creo que a nuestro juego le va bien la narrativa en espina, con muchos caminos secundarios pero con una historia medianamente lineal.

**Comment by Alba-Munoz** [comment]
Hemos pensado, que tal vez deberíamos dejarlo con un único final, seguir una historia lineal con bifurcaciones, pero que al final llegues al mismo punto, porque creemos que hacer dos finales al fin y al cabo no tenemos muy claro que otro final se pondría y a la hora de programar seguro que es un lio

**Comment by silviamarugan** [comment]
Que os parece así?

NUESTRO LEMA: Una aventura con toques de accion y RPG en la que el agua y la naturaleza tienen un papel clave.

HISTORIA: "Nos encontramos en el año 2054, dentro del bosque Iaur, ubicado en un país nordico muy lejano. En este bosque viven animales muy diversos, en armonía y en paz. Las almas de aquellos que mueren llegan al más allá a través del Árbol Hëra (Juira), suben hasta la copa y se acaban canalizando en frutas de la vida y se encargan de mantener la armonía en el bosque desde el más allá. La humanidad encontró este árbol y acabo comercializando esta fruta cada vez más cuando caía al suelo, pero llegó un punto en el que querían más y más y llegaron a talar el árbol para conseguir las frutas más altas. A partir de aquello, nadie se encargaba de mantener el bosque excepto los animales, ya que las almas no podían descansar en paz y se quedaban en un limbo eterno. Los animales terrenales no podían con todo lo que los humanos hacían a ese bosque, así que todo acabó deteriorándose más y más.
Los humanos visitaban el bosque constantemente, de vez en cuando por ocio, de vez en cuando por caza, pero de alguna manera siempre acababan perjudicandolo. Dejaban basura, quemaban árboles y plantas, mataban animales a sangre fría y por diversión, destruían lugares para convertirlos en edificios gigantes y otras muchas cosas más. El bosque acabó siendo más pequeño, pero además, más oscuro, vacío, triste. Sólo había unas pocas zonas que no habían sido descubiertas por los humanos que seguían alegres y llenas de naturaleza.
En un momento, unos humanos decidieron acampar en un lugar del bosque. Llevaban armas y disfrutaban de matar animales, pero no eran cazadores. Un zorro llamado Neerah se escabulló en unos arbustos cercanos para observar su comportamiento por si eran peligrosos, pero uno de ellos se dio cuenta, sacó un arma y le mató. Poco a poco, fue matando a los otros zorros que esperaban una alerta o una buena noticia.
Neerah no se convirtió en un alma normal, le reconocomia el no haber dado el aviso de aquello que pasó. Quizas por ello despertaba cada 100 años en el mismo lugar en el cual pasó y vagaba por las zonas en las que pasaba en vida. De vez en cuando se encontraba más almas en pena, pero al cabo de un rato se esfumaban; eran más débiles que ella.
Una de estas veces, por pura casualidad, se despertó y se dio cuenta de lo mal que estaba todo el bosque; vio a animales sufriendo, la forestación sucia, quemada y llena de basura, y pensó que quizas si hacía algo al respecto su alma descansaría en paz por fin. Aunque, ¿como lo haría ella sola si es un alma solitaria vagando por ahí y ni siquiera sabe por dónde empezar? Por otra casualidad de la vida, pudo oir a lo lejos unas ramas que se caian en un arbusto. Se acercó y en un segundo una pequeña bola de luz salio de ahi. Era otra alma en pena, la cual tenía las mismas intenciones que ella pero no podía salir de la aldea ya que se encargaba de que no se viniera abajo. Las dos hablaron y la extraña bola de luz le enseñó lo que podía hacer, como transformarse en otros animales. Después de un rato Neerah partió hacia la montaña más alta, en la cual aquella bola le dijo que encontraría la paz. En el camino, se encuentra a una ardilla moribunda, que le pide que se lleve su alma con ella y la use bien. Neerah la usa y se da cuenta de que ahora puede moverse de manera más ágil, aunque por tiempo limitado porque es un alma muy vieja.
Así, nuestra protagonista va avanzando por la historia, ayudando a animales a encontrar la paz y además, combatiendo a humanos para saciar su sed de venganza. Podrá teletransportarse por el mapa mediante el agua. Este elemento le sirve tambien para purificar las almas de los animales en pena y guardar las almas de los humanos en un lugar seguro para que jamás vuelvan a renacer. Estas almas le van a perimtir abrir puertas, pasadizos, bloqueos o incluso llegar a zonas a las cuales no podría llegar sin ellas.
Después de todos los combates contra el terrible Pescador, el Cazador, el Amo de Cuervos, el Campista y la Mujer de los Lobos, además de todos los problemas ajenos en los que ha ayudado, nuestra protagonista llega a la montaña, purifica todas las almas que ha reunido y empieza a nevar mientras se la ve en la escena final, se acaba viendo todo el mapa por el cual hemos pasado. El alma de Neerah se esfuma y se convierte en una bola de luz, junto a las almas que has purificado, se reúnen todas en forma de árbol y avivan el bosque."

PLOT POINTS: La destruccion del arbol Hëra. La muerte de Neerâh. Su resurrección. El momento en el que descubre que la bolita es el espiritu de su madre. Dialogos que pueden cambiar tu percepcion de las cosas (?) Neerâh descansando en paz. El renacimiento del gran arbol.

TIPO DE NARRATIVA: Como narrativa, creo que a nuestro juego le va bien la narrativa en espina, con muchos caminos secundarios pero con una historia medianamente lineal.

**Comment by igallegocalvo** [comment]
Por mi todo ok.
En cuanto a los **plot points** creo que podemos añadir otro cuando aprende a utilizar las almas de otros animales para transformarse. Y quizá otro al derrotar al primer boss, que obtengamos algo o se restaure parte del ecosistema...

**Comment by silviamarugan** [comment]
Perfecto, lo cambio en un momento y cierro issue.

**Comment by silviamarugan** [comment]
NUESTRO LEMA: Una aventura con toques de accion y RPG en la que el agua y la naturaleza tienen un papel clave.

HISTORIA: "Nos encontramos en el año 2054, dentro del bosque Iaur, ubicado en un país nordico muy lejano. En este bosque viven animales muy diversos, en armonía y en paz. Las almas de aquellos que mueren llegan al más allá a través del Árbol Hëra (Juira), suben hasta la copa y se acaban canalizando en frutas de la vida y se encargan de mantener la armonía en el bosque desde el más allá. La humanidad encontró este árbol y acabo comercializando esta fruta cada vez más cuando caía al suelo, pero llegó un punto en el que querían más y más y llegaron a talar el árbol para conseguir las frutas más altas. A partir de aquello, nadie se encargaba de mantener el bosque excepto los animales, ya que las almas no podían descansar en paz y se quedaban en un limbo eterno. Los animales terrenales no podían con todo lo que los humanos hacían a ese bosque, así que todo acabó deteriorándose más y más.
Los humanos visitaban el bosque constantemente, de vez en cuando por ocio, de vez en cuando por caza, pero de alguna manera siempre acababan perjudicandolo. Dejaban basura, quemaban árboles y plantas, mataban animales a sangre fría y por diversión, destruían lugares para convertirlos en edificios gigantes y otras muchas cosas más. El bosque acabó siendo más pequeño, pero además, más oscuro, vacío, triste. Sólo había unas pocas zonas que no habían sido descubiertas por los humanos que seguían alegres y llenas de naturaleza.
En un momento, unos humanos decidieron acampar en un lugar del bosque. Llevaban armas y disfrutaban de matar animales, pero no eran cazadores. Un zorro llamado Neerah se escabulló en unos arbustos cercanos para observar su comportamiento por si eran peligrosos, pero uno de ellos se dio cuenta, sacó un arma y le mató. Poco a poco, fue matando a los otros zorros que esperaban una alerta o una buena noticia.
Neerah no se convirtió en un alma normal, le reconocomia el no haber dado el aviso de aquello que pasó. Quizas por ello despertaba cada 100 años en el mismo lugar en el cual pasó y vagaba por las zonas en las que pasaba en vida. De vez en cuando se encontraba más almas en pena, pero al cabo de un rato se esfumaban; eran más débiles que ella.
Una de estas veces, por pura casualidad, se despertó y se dio cuenta de lo mal que estaba todo el bosque; vio a animales sufriendo, la forestación sucia, quemada y llena de basura, y pensó que quizas si hacía algo al respecto su alma descansaría en paz por fin. Aunque, ¿como lo haría ella sola si es un alma solitaria vagando por ahí y ni siquiera sabe por dónde empezar? Por otra casualidad de la vida, pudo oir a lo lejos unas ramas que se caian en un arbusto. Se acercó y en un segundo una pequeña bola de luz salio de ahi. Era otra alma en pena, la cual tenía las mismas intenciones que ella pero no podía salir de la aldea ya que se encargaba de que no se viniera abajo. Las dos hablaron y la extraña bola de luz le enseñó lo que podía hacer, como transformarse en otros animales. Después de un rato Neerah partió hacia la montaña más alta, en la cual aquella bola le dijo que encontraría la paz. En el camino, se encuentra a una ardilla moribunda, que le pide que se lleve su alma con ella y la use bien. Neerah la usa y se da cuenta de que ahora puede moverse de manera más ágil, aunque por tiempo limitado porque es un alma muy vieja.
Así, nuestra protagonista va avanzando por la historia, ayudando a animales a encontrar la paz y además, combatiendo a humanos para saciar su sed de venganza. Podrá teletransportarse por el mapa mediante el agua. Este elemento le sirve tambien para purificar las almas de los animales en pena y guardar las almas de los humanos en un lugar seguro para que jamás vuelvan a renacer. Estas almas le van a perimtir abrir puertas, pasadizos, bloqueos o incluso llegar a zonas a las cuales no podría llegar sin ellas.
Después de todos los combates contra el terrible Pescador, el Cazador, el Amo de Cuervos, el Campista y la Mujer de los Lobos, además de todos los problemas ajenos en los que ha ayudado, nuestra protagonista llega a la montaña, purifica todas las almas que ha reunido y empieza a nevar mientras se la ve en la escena final, se acaba viendo todo el mapa por el cual hemos pasado. El alma de Neerah se esfuma y se convierte en una bola de luz, junto a las almas que has purificado, se reúnen todas en forma de árbol y avivan el bosque."

PLOT POINTS: La destruccion del arbol Hëra. La muerte de Neerâh. Su resurrección. Aprendizaje sobre como funcionan las almas. Derrota del primer boss, desbloqueo de la "Tienda de la Parca". El momento en el que descubre que la bolita es el espiritu de su madre. Dialogos que pueden cambiar tu percepcion de las cosas. Neerâh descansando en paz. El renacimiento del gran arbol.

TIPO DE NARRATIVA: Como narrativa, creo que a nuestro juego le va bien la narrativa en espina, con muchos caminos secundarios pero con una historia medianamente lineal.
