### ISSUE TITLE
Personajes

### ISSUE THREAD

**Issue by igallegocalvo** [CIFP-Jose-luis-Garci/Thawnen#6]
- [x] Personajes jugables: Historia, aspecto gráfico, características, habilidades
- [x] NPC´s: Historia, aspecto gráfico, características, habilidades
- [x] Enemigos: Historia, aspecto gráfico, características, habilidades

**Comment by silviamarugan** [comment]
Nuestro único **personaje jugable** será Neerâh,  la cual es un zorro ártico. Su historia ya esta contada en el apartado de historia general (https://github.com/CIFP-Jose-luis-Garci/Thawnen/issues/5). Su aspecto gráfico es translucido, con tonos más cálidos o más frios dependiendo de la forma que tenga. Tiene dos tipos de habilidades, pasivas y activas. Las pasivas son las que nunca se van ya que son suyas, la cual es absorber almas. Las activas son las que le ofrecen los otros animales del bosque con sus almas como volar, nadar, agilidad, camuflaje, fuerza bruta, cabezazo mortal y visión nocturna.

**Comment by silviamarugan** [comment]
En cuanto a los NPCs, tenemos los siguientes:

- Bolita Madre ( llamada **_Naneth_**) , la cual estuvo en otra crisis que hubo entre los animales del Gran Bosque y los salvó a todos dando su vida. Subió a la montaña del descanso y se convirtió en una fusión de todas las almas a las que ayudó. Fue la madre de Neerâh pero, por su forma, Neerâh no la reconoció hasta pasado un tiempo. 
- La Parca de la Tienda (Hadbyss) y su perro. Su situación es que está debil por el frio que hace en el mundo terrenal, ya que lleva mucho tiempo vagando por el por no poder volver a su tierra por esa falta de fuerzas. Recluta a Neerâh para que le traiga almas a cambio de utiles que tenía en su mochila y que consiguió de las almas que morían y bajaban al inframundo. Le consumió la vagueza, asi que ya no consigue almas por ella misma ni tampoco las lleva bajo tierra, lo hace su perro de huesos. Su estética es la típica capa de muerte, normalmente lleva una taza de café o té y una manta puesta por encima, además lleva pantuflas de conejos rosas. 

NPCs secundarios:
- El cuervo (Kråken), el cual es simplemente un cuervo negro el cual perdió a sus crias porque un campista usó sus huevos para hacerse una tortilla. Nos da la habilidad de volar.
- La ardilla (Grag), la cual se quedó atrapada en una trampa para osos. Nos da la habilidad de ser más agiles.
- El salmón (Laks), el cual se queda atrapado en el afluente seco del rio principal, además de haber tragado plastico. Nos da la habilidad de nadar.
- Camaleón (Kamele). Fue abandonado a su suerte por un niño que fue de acampada al bosque y que ya no le queria. Nos da la habilidad de camuflaje.
- Oso (Bjorno Jovannah). No puede comer porque el rio se seco. Bajo al pueblo a encontrar comida y le pegaron un tiro. Nos permite tener fuerza bruta.
- Reno (Dyhorn). Se infecta con caquexia crónica, agoniza hasta su muerte. Nos da el cabezazo mortal.
- Buho (Ulé). Solo está mayor. Nos esta esperando desde hace tiempo para llevarnos su alma y quedarse en paz. Nos da la habilidad de visión nocturna.
- Gato (Kitty Katte). Perdió sus 6 primeras vidas y, como ya conoció a la muerte tantisimas veces, ya no quiere vivir la ultima que le queda, asi que nos pide que acabemos con el. Nos da la habilidad del sigilo. 

Sus esteticas son low poly y fieles a la realidad (en cuanto a colores, por ejemplo la ardilla, el oso y el reno serán marrones, el buho gris, el camaleon verde, etc)

**Comment by Alba-Munoz** [comment]
**Bosses** 
- Un Cazador
- Un pescador
- Campista

**El pescador**: Primer y tercer boss 
Con el pescador vamos a luchar dos veces, La primera vez este se encuentra a orillas de un lago y Neerâh le espanta los peces por lo que se enfada y le ataca. La segunda vez, el pescador esta en una barca en mitad de un lago y Neerâh al hacer un teletransporte le tira de la barca y comienza la pelea.

El pescador es un señor mayor con sobrepeso, lleva un peto de pesca con varios accesorios de pesca colgando, también lleva un gorro y una caña de pescar.

En combate la caña la usara como látigo para hacer daño o como lazo para atrapar al personaje y dejarle un tiempo inmovilizado. 
También puede invocar cosas como un barco, un pez gigante, una ola de peces y una pistola de agua.(También hacen daño)


**El campista:** Segundo boss
Esta en un viaje de fin de curso con sus compañeros, estos dejan el lugar en el que están lleno de basura, el campista se aparta del grupo para ir al baño y se pierde, lleva solo por el bosque una semana, Neerâh lo intenta ayudar, pero le da un ataque psicótico sumado con la ansiedad de llevar perdido tanto tiempo que se piensa que Neerâh es comida y le ataca.

El campista es un joven con ropa de campo, lleva gafas super empañadas y no ve nada.

Con este boss se lucha de noche. El lleva  un farolillo, lo va tirando para iluminar una zona e ir a ella, un ataque especial es que tira un farolillo y este se prende fuego al romperse, para aturdir lo que hará será tirarle ropa sucia a Neerâh.


**El cazador:**Último boss
Es un padre de familia que vive en una aldea, a esa aldea baja un oso a por comida los aldeanos se asustan y le llaman para que acabe con la vida del oso.

El cazador lleva barba, un chaleco de camuflaje con chapas con temática de caza y armas.

En combate este personaje puede ir cambiando sus armas (escopeta, rifle...) parta crear distintos tipos de ataque y al llevar ropa de camuflaje, tiene la habilidad de dentro de nuestro campo de visión  desaparecer y atacar sin que nosotros le veamos.

**Comment by InGar-Akuma** [comment]
**Mini Bosses:**
- Jegerinne, una cazadora de lobos.
- Amo de Cuervos.
- Vikingo decapitado

**Jegerinne**
Jegerinne es el primer mini boss con el que se peleará Neerâh, a modo de tutorial. Es una representación de las amenazas que sufrían los animales del bosque en el pasado, en base a los recuerdos de Naneth. Es una cazadora de lobos, por lo que su vestimenta está hecha de su piel y lleva una cabeza de lobo como gorro, que cubre sus trenzas vikingas. Lleva un arco.

Sus habilidades son _Intimidación_  y _Tiro de flechas_. Con Intimidación, Neerâh no podrá moverse durante unos segundos.  Con Tiro de flechas, Jagerinne usa su arco para disparar flechas.

**Amo de Cuervos**
Amo de Cuervos es una persona obsesionada con los cuervos, hasta tal punto que se ha sumido en la locura. Lleva una máscara de médico de la peste, una túnica y un bastón con temática de cuervo.

Sus habilidades son _Horda de cuervos_ y _Bastón atizador_. Con _Horda de cuervos_  invocará a muchos cuervos que atacarán en conjunto. Con _Bastón atizador_ usará su bastón para atacar.

**Vikingo decapitado**
Es un cuerpo de un vikingo que lleva siglos buscando su cabeza. Vive en una cueva mágica, lo que le ha permitido seguir con vida. Lleva una lanza como arma y un escudo. Va montado sobre el reno con caquexia.

Sus habilidades son _Ataque con lanza_ y _Embestida_. Con _Ataque con lanza_ hará ataques en área desde el reno. Con _Embestida_ el reno hará ataques rápidos embistiendo, chocará con las paredes de la cueva y caerán piedras.
