### ISSUE TITLE
Estilo visual

### ISSUE THREAD

**Issue by igallegocalvo** [CIFP-Jose-luis-Garci/Thawnen#7]
- [x] Concept art
- [x] Diseño de personajes
- [x] Diseño de escenarios
- [x] Objetos, armas, power up, coleccionables…
- [x] Otros: mapas, botones…

**Comment by Alba-Munoz** [comment]
Mini boss arquera

(si queréis cambiar algo me lo decís)

![Ar](https://user-images.githubusercontent.com/78143652/141374613-9d6d2daf-b038-44ad-bb8e-b51b55605b8a.jpg)

**Comment by silviamarugan** [comment]
![1636669462739-01.jpeg](https://user-images.githubusercontent.com/77985556/141379070-bb72005f-0b8d-408d-9f07-b096c931852a.jpeg) 
Concept rápido del pescador, es una idea de la estética y la paleta de colores que llevara este personaje

**Comment by silviamarugan** [comment]
También he hecho un concept del escenario general de la aldea a la que nos llevará la bola de luz

![1636572587315-01.jpeg](https://user-images.githubusercontent.com/77985556/141379169-0f2fbd23-99ef-4ed5-a114-20b9c4b16609.jpeg)

**Comment by InGar-Akuma** [comment]
Concept art de la parca:
![3285c3f1-9f41-4720-a64e-fda75d5ddb5b.png](https://user-images.githubusercontent.com/77485516/141457169-cfc1248d-a71b-4eb3-86f3-4caf9d99f96c.png)

**Comment by InGar-Akuma** [comment]
Mapa
![Thawnen (2)](https://user-images.githubusercontent.com/77485516/141507952-de0a9d25-7f1b-49e8-b916-f2b61b004368.jpg)

**Comment by InGar-Akuma** [comment]
Almas
<img width="120" alt="AlmasRecurso 3@2x" src="https://user-images.githubusercontent.com/77485516/141508323-5f299828-6285-4064-a0dd-ffd444101036.png">

**Comment by InGar-Akuma** [comment]
Brújula (marcará la dirección general)
<img width="942" alt="BrujulaRecurso 4@2x" src="https://user-images.githubusercontent.com/77485516/141509089-c676a0ef-91d0-40ac-9acf-df53c068a1c4.png">

**Comment by InGar-Akuma** [comment]
Barra de vida
<img width="355" alt="VidaRecurso 1@2x" src="https://user-images.githubusercontent.com/77485516/141509153-22f5f07a-9eb7-4f5f-b48f-af30854b557f.png">

**Comment by silviamarugan** [comment]
Aquí dejo la estética que tendrán los escenarios:

Bosque: 
![PicsArt_11-12-06.31.10.png](https://user-images.githubusercontent.com/77985556/141511072-ad7d2c78-7fdd-4979-a230-08d400de48e1.png)
Lago:
![PicsArt_11-12-06.40.59.jpg](https://user-images.githubusercontent.com/77985556/141511112-6a641c28-7870-4399-a6b8-2cdbd252233a.jpg)
Otra parte del bosque:
![PicsArt_11-12-06.40.38.jpg](https://user-images.githubusercontent.com/77985556/141511137-ab20af88-2d13-47fc-b04a-9ccdcb019f7c.jpg)
Montaña nevada:
![PicsArt_11-12-06.39.52.jpg](https://user-images.githubusercontent.com/77985556/141511198-1718b38b-1e4d-41a5-ba6a-795fd4bb426a.jpg)
Cueva:
![PicsArt_11-12-06.39.05.jpg](https://user-images.githubusercontent.com/77985556/141511229-36be041c-1c10-4411-960f-8439d1dc9287.jpg)
Lago:
![PicsArt_11-12-06.39.30.jpg](https://user-images.githubusercontent.com/77985556/141511257-0f41454f-a05b-4626-acd9-1f47fe51834b.jpg)
Pueblo (en caso de que se vea)
![PicsArt_11-12-06.34.18.jpg](https://user-images.githubusercontent.com/77985556/141511311-9aa89d48-4a0b-495c-8fc7-bd9f00f609fb.jpg)
Bosque corrupto:
![PicsArt_11-12-06.32.57.jpg](https://user-images.githubusercontent.com/77985556/141511351-4058a331-1518-4055-8c0d-3a91e6733c49.jpg)
Más montaña:
![PicsArt_11-12-06.32.46.jpg](https://user-images.githubusercontent.com/77985556/141511380-ed77f103-eea0-4c1e-bd49-2e0be3897a93.jpg)
Campo de setas:
![PicsArt_11-12-06.30.27.jpg](https://user-images.githubusercontent.com/77985556/141511476-0b5a40d0-3150-4326-8ac1-29c889aeacd9.jpg)
Otra montaña con nieve:
![PicsArt_11-12-06.40.15.jpg](https://user-images.githubusercontent.com/77985556/141511534-91e2a27f-d8fc-4b6b-89b9-b23a238ae87b.jpg)

**Comment by Alba-Munoz** [comment]
Neerâh

![Ilustración42](https://user-images.githubusercontent.com/78143652/141524044-c72313c5-997f-42c7-9437-ac1e81eabe7e.jpg)

**Comment by InGar-Akuma** [comment]
Los botones serán de solo texto, como este:

![Boton (2)](https://user-images.githubusercontent.com/77485516/141525187-e744f17e-59ce-496d-a6fb-db32b10668a6.png)


Para indicar que está seleccionado, aparecerá una huella de zorro en ese botón y un leve brillo por detrás.

**Comment by InGar-Akuma** [comment]
En cuanto a los coleccionables, serán objetos cotidianos, como un reloj de bolsillo, una cantimplora, un mechero, etc.
