### ISSUE TITLE
Interfaz

### ISSUE THREAD

**Issue by igallegocalvo** [CIFP-Jose-luis-Garci/Thawnen#8]
- [x] Mapa de navegación: diagrama de bloques donde se muestre la navegación del usuario durante el juego
- [x] Menús
- [x] HUD

**Comment by InGar-Akuma** [comment]
**HUD**

Durante la aventura
![HUD_3](https://user-images.githubusercontent.com/77485516/141265141-d668c570-19b8-494d-9a7a-888c6c353f67.jpg)

**Comment by igallegocalvo** [comment]
**MAPA DE NAVEGACIÓN**

![flujoJuego](https://user-images.githubusercontent.com/77749840/141277373-73eac854-9aa3-40bf-ab2a-4f7d5ae6d1ce.png)

**Comment by igallegocalvo** [comment]
**HUD**

Durante los diálogos sería similar a esto, un bocadillo con el texto y una miniatura del personaje que habla.
![okami_02](https://user-images.githubusercontent.com/77749840/141279227-faa3c2da-8439-45bb-bb0c-83456abc1146.jpg)

**Comment by InGar-Akuma** [comment]
Menú de Inicio

![Inicio2](https://user-images.githubusercontent.com/77485516/141523233-4f941626-51ce-42a8-a330-da22bdd69b5f.png)


Menú de pausa

![Pause2](https://user-images.githubusercontent.com/77485516/141523209-1f4a76fb-d7ad-4068-a92f-6ce19f033662.png)


Pantalla de carga

![Loading](https://user-images.githubusercontent.com/77485516/141514743-4bd2c9b6-7df9-466d-971e-bc9db0f6918c.png)

**Comment by InGar-Akuma** [comment]
Galería
![Gallery](https://user-images.githubusercontent.com/77485516/141521154-4eeaaf13-9b63-4209-98ff-0dbded6c08f2.png)

**Comment by InGar-Akuma** [comment]
Coleccionables
![Collectibles](https://user-images.githubusercontent.com/77485516/141525515-5447acd8-d607-4d4a-b978-fd530420ae0d.png)
