### ISSUE TITLE
Dinámicas y mecánicas

### ISSUE THREAD

**Issue by igallegocalvo** [CIFP-Jose-luis-Garci/Thawnen#9]
Explicar las dinámicas y mecánicas del juego

**Comment by sxrgi0** [comment]
**MECÁNICAS**

-Recolección de almas. 
-Enfrentamientos con humanos, minibosses y bosses.
-Exploración de distintos caminos secundarios.
-Poder transformarse en distintos animales.

**DINÁMICAS**

-Recompensas (Power UPs, conseguidos con la recolección de almas).
-Logros, podemos añadir logros al jugador cuando consiga la primera muerte o mate al primer boss.
-Sensación de progreso, utilizar un número determinado de almas para poder cruzar por una zona secundaria.

**Comment by vcalzadaga** [comment]
Esto necesito que me lo desarrolléis más teniendo en cuenta lo que hemos visto en clase. No os limitéis simplemente a hacer un listado de dinámicas y mecánicas.

Explicad con detalle cómo van a funcionar esas mecánicas en vuestro juego, qué va a tener que hacer el jugador, cómo van a ser los enfrentamientos, en qué consiste la recolección de almas...

**Comment by sxrgi0** [comment]
Recolección de almas. Existen dos tipos de almas, las de sangre y las puras. Las almas de sangre las conseguimos matando a humanos con furia por la destrucción de su hogar, y las almas puras las conseguimos ayudando a morir y buscar la paz a otros animales que están moribundos por la corrupción del bosque, así no tendrán que despertar y ver el terror cada cierto tiempo como nuestro protagonista.

Exploración de distintos caminos secundarios. El jugador tendrá la posibilidad de explorar el mapa para encontrar otros caminos secundarios y hacer misiones que no influyen en la historia principal del juego. 
**MECÁNICAS**

Transformación en distintos animales. El jugador podrá transformarse en distintos animales del bosque, para conseguir las almas de estos animales tendrá que realizar una misión que este animal le pedirá o simplemente desbloquearlo al llevar las almas recolectadas a los lagos.

Enfrentamientos. El jugador en cada nivel tendrá que enfrentarse a varios enemigos. A parte de estos enemigos, se enfrentará a un jefe intermedio y al final, se enfrentará al jefe final. Al enfrentarse a estos enemigos recolectará almas de sangre.

**DINÁMICAS**

Recompensas. Se recompensará al jugador con los Power Ups. Las almas de sangre le otorgarán más vida al jugador, mientras que las almas puras le otorgarán más escudo.

Logros. El jugador conseguirá distintos logros a lo largo del juego. Por ejemplo, cuando el jugador mate al primer enemigo conseguirá un logro de Primera sangre.

Sensación del progreso. Durante el juego, el jugador podrá encontrarse con caminos por los que no podrá cruzar ya que requieren una cantidad de almas específica. El jugador podrá obviar este camino y seguir adelante o podrá esperar a recolectar las almas necesarias para desbloquear el camino.

**Comment by sxrgi0** [comment]
**MECÁNICAS**

Recolección de almas. Existen dos tipos de almas, las de sangre y las puras. Las almas de sangre las conseguimos matando a humanos con furia por la destrucción de su hogar, y las almas puras las conseguimos ayudando a morir y buscar la paz a otros animales que están moribundos por la corrupción del bosque, así no tendrán que despertar y ver el terror cada cierto tiempo como nuestro protagonista.

Exploración de distintos caminos secundarios. El jugador tendrá la posibilidad de explorar el mapa para encontrar otros caminos secundarios y hacer misiones que no influyen en la historia principal del juego. 


Transformación en distintos animales. El jugador podrá transformarse en distintos animales del bosque, para conseguir las almas de estos animales tendrá que realizar una misión que este animal le pedirá o simplemente desbloquearlo al llevar las almas recolectadas a los lagos.

Enfrentamientos. El jugador en cada nivel tendrá que enfrentarse a varios enemigos. A parte de estos enemigos, se enfrentará a un jefe intermedio y al final, se enfrentará al jefe final. Al enfrentarse a estos enemigos recolectará almas de sangre.

**DINÁMICAS**

Recompensas. Se recompensará al jugador con los Power Ups. Las almas de sangre le otorgarán más vida al jugador, mientras que las almas puras le otorgarán más escudo.

Logros. El jugador conseguirá distintos logros a lo largo del juego. Por ejemplo, cuando el jugador mate al primer enemigo conseguirá un logro de Primera sangre.

Sensación del progreso. Durante el juego, el jugador podrá encontrarse con caminos por los que no podrá cruzar ya que requieren una cantidad de almas específica. El jugador podrá obviar este camino y seguir adelante o podrá esperar a recolectar las almas necesarias para desbloquear el camino.
